# Source: MindYOLO (https://github.com/mindspore-lab/mindyolo)
# License: Apache 2.0

####################
# yolov8-base.yaml #
####################

epochs: 500  # total train epochs
per_batch_size: 16  # 16 * 8 = 128
img_size: 640
iou_thres: 0.7
conf_free: True
sync_bn: True
anchor_base: False
opencv_threads_num: 0  # opencv: disable threading optimizations

network:
  model_name: yolov8
  nc: 80  # number of classes
  reg_max: 16

  stride: [8, 16, 32]

  # yolov8s
  depth_multiple: 0.33  # scales module repeats
  width_multiple: 0.50  # scales convolution channels
  max_channels: 1024

  checkpoint: "../checkpoints/yolov8s.ckpt"

  # YOLOv8.0n backbone
  backbone:
    # [from, repeats, module, args]
    - [-1, 1, ConvNormAct, [64, 3, 2]]  # 0-P1/2
    - [-1, 1, ConvNormAct, [128, 3, 2]]  # 1-P2/4
    - [-1, 3, C2f, [128, True]]
    - [-1, 1, ConvNormAct, [256, 3, 2]]  # 3-P3/8
    - [-1, 6, C2f, [256, True]]
    - [-1, 1, ConvNormAct, [512, 3, 2]]  # 5-P4/16
    - [-1, 6, C2f, [512, True]]
    - [-1, 1, ConvNormAct, [1024, 3, 2]]  # 7-P5/32
    - [-1, 3, C2f, [1024, True]]
    - [-1, 1, SPPF, [1024, 5]]  # 9

  # YOLOv8.0n head
  head:
    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
    - [-1, 3, C2f, [512]]  # 12

    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 4], 1, Concat, [1] ]  # cat backbone P3
    - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

    - [-1, 1, ConvNormAct, [256, 3, 2]]
    - [[ -1, 12], 1, Concat, [1]]  # cat head P4
    - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

    - [-1, 1, ConvNormAct, [512, 3, 2]]
    - [[-1, 9], 1, Concat, [1]]  # cat head P5
    - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

    - [[15, 18, 21], 1, YOLOv8Head, [nc, reg_max, stride]]  # Detect(P3, P4, P5)

########################
# hyp.scratch.low.yaml #
########################

optimizer:
  optimizer: momentum
  lr_init: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  momentum: 0.937  # SGD momentum/Adam beta1
  nesterov: True  # update gradients with NAG(Nesterov Accelerated Gradient) algorithm
  loss_scale: 1.0  # loss scale for optimizer
  warmup_epochs: 3  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  min_warmup_step: 1000  # minimum warmup step
  group_param: yolov8  # group param strategy
  gp_weight_decay: 0.0005  # group param weight decay 5e-4
  start_factor: 1.0
  end_factor: 0.01

loss:
  name: YOLOv8Loss
  box: 7.5  # box loss gain
  cls: 0.5  # cls loss gain
  dfl: 1.5  # dfl loss gain
  reg_max: 16

data:
  num_parallel_workers: 4

#############
# coco.yaml #
#############

# COCO 2017 dataset http://cocodataset.org

  dataset_name: coco

  train_set: ./coco/train2017.txt  # 118287 images
  val_set: ./coco/val2017.txt  # 5000 images
  test_set: ./coco/test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

  nc: 80

  # class names
  names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
           'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
           'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
           'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
           'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
           'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
           'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
           'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
           'hair drier', 'toothbrush' ]
